name: Release

on:
  push:
    branches:
      - main
      - prerelease
      - test

jobs:
  release:
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    uses: zanminkian/github-actions/.github/workflows/release.yml@main
    secrets: inherit
  test:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.release.outputs.published }}
