name: Release

on:
  push:
    branches:
      - main
      - prerelease

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    uses: zanminkian/github-actions/.github/workflows/release.yml@main
    secrets: inherit
